### ISSUE TITLE
On OSX, can not find libigl

### ISSUE THREAD

**Issue by edwinchenyj** [dilevin/GAUSS#18]
libigl is downloaded with 
    git clone --recursive https://github.com/dilevin/GAUSS.git
and located in GAUSS/extern, but missing while compiling:

first error:
fatal error: 
      'igl/grid.h' file not found

**Comment by dilevin** [comment]
nvm I see the problem. A fix is in the works.

**Comment by dilevin** [comment]
Fixed with new .gitmodules file. 

You will need to reinitialize  your repo by running:
git submodule update --init --recursive
git submodule update --recursive --remote
