### ISSUE TITLE
Undefined function or variable 'WorldFEM_Interface'.

### ISSUE THREAD

**Issue by Rupemgera** [dilevin/GAUSS#55]
I have built the Matlab project, then run example8.m
Then an error appeared
```>> example8
Warning: The following error was caught while executing 'WorldFEM' class destructor:
Undefined function 'WorldFEM_Interface' for input arguments of type 'char'.

Error in WorldFEM/delete (line 15)
            WorldFEM_Interface('delete', this.objectHandle);

Error in WorldFEM (line 8)
        function this = WorldFEM(varargin)

Error in example8 (line 11)
fem = WorldFEM('stvk_linear_tetrahedra', DT.Points, DT.ConnectivityList); 
> In WorldFEM (line 8)
  In example8 (line 11) 
Undefined function or variable 'WorldFEM_Interface'.

Error in WorldFEM (line 10)
            this.objectHandle = WorldFEM_Interface('new', varargin{:});

Error in example8 (line 11)
fem = WorldFEM('stvk_linear_tetrahedra', DT.Points, DT.ConnectivityList);
```

**Comment by dilevin** [comment]
Did you add Gauss to your matlab path ?

From the instructions:

addpath('{Gauss_Root_Dir}/src/MATLAB/')
addpath('{Gauss_Root_Dir}/build/lib/{Build_Mode_of_Gauss_MATLAB}/')
savepath

**Comment by Rupemgera** [comment]
> Did you add Gauss to your matlab path ?
> From the instructions:
> addpath('{Gauss_Root_Dir}/src/MATLAB/')
> addpath('{Gauss_Root_Dir}/build/lib/{Build_Mode_of_Gauss_MATLAB}/')
> savepath

yes, I have added them to my MATLAB path.
I ran example8.m, and MATLAB could call WorldFEM correctly but could not call WorldFEM_Interface

**Comment by dilevin** [comment]
Just for my own clarification ... worldFEM is calling worldFEM interface ... you aren’t calling it directly right ?

**Comment by Rupemgera** [comment]
> Just for my own clarification ... worldFEM is calling worldFEM interface ... you aren’t calling it directly right ?

I just ran example8.m. I meant that MATLAB can find worldFEM but can't find worldFEM interface.

those files are in build/lib/debug fold:
- Base.lib/pdb
- Core.lib.pdb

- FEM.lib/pdb

- ParticleSystem.lib/pdb

- SolversLinear.lib/pdb 

- WorldFEM_interface.exp/lib

May it be that I didn't compile it right?

**Comment by Rupemgera** [comment]
I moved files in GAUSS/build/bin/Debug, GAUSS/build/lib/Debug and GAUSS/src/MATLAB into one fold, then ran example8.m(also in that fold). and it worked. 
So it seems that my MATLAB didn't work though I added those path to search path.
And, by the way, files in GAUSS/build/bin/Debug should also be added to search path.
